# Generated by Django 5.1.2 on 2024-10-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('cilindrada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_corrida', models.DateField()),
                ('localizacao', models.CharField(max_length=200)),
                ('motos_participantes', models.ManyToManyField(to='gerenciamento.moto')),
            ],
        ),
        migrations.AddField(
            model_name='moto',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.piloto'),
        ),
    ]
